# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
prepare_react_native_project!

# Force use of static frameworks for better ML Kit compatibility
use_frameworks! :linkage => :static

# Override Firebase SDK version
$FirebaseSDKVersion = '11.15.0'

target 'RNMLKitExample' do
  project 'RNMLKitExample.xcodeproj'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase and ML Kit pods
  pod 'Firebase/Core', '~> 11.15.0'
  pod 'GoogleMLKit/BarcodeScanning', '~> 7.0.0'
  pod 'GoogleMLKit/FaceDetection', '~> 7.0.0'
  pod 'GoogleMLKit/ImageLabeling', '~> 7.0.0'
  pod 'GoogleMLKit/TextRecognition', '~> 7.0.0'
  pod 'GoogleMLKit/TextRecognitionChinese', '~> 7.0.0'
  pod 'GoogleMLKit/TextRecognitionDevanagari', '~> 7.0.0'
  pod 'GoogleMLKit/TextRecognitionJapanese', '~> 7.0.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '~> 7.0.0'
  pod 'GoogleMLKit/Translate', '~> 7.0.0'
  pod 'GoogleMLKit/LanguageID', '~> 7.0.0'

  target 'RNMLKitExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        
        # Fix for Firebase and ML Kit
        if target.name.start_with?('Firebase', 'GoogleMLKit', 'MLKit', 'GoogleDataTransport', 'GoogleUtilities')
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        end
      end
    end
  end
end